name: global-workflow

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      is_valid: true
    steps:
      - name: Say Hello
        run: echo "Hello, World!"

  publish-message:
    runs-on: ubuntu-latest
    needs: validate
    if: |
      fromJSON(needs.validate.outputs.is_valid) == true &&
      github.event.pull_request.merged == true
    steps:
      - name: Say Hello
        run: echo "Publishing..."

  error-handler:
    runs-on: ubuntu-latest
    needs: validate
    if: |
      fromJSON(needs.validate.outputs.is_valid) == false
    steps:
      - name: Say Hello
        run: echo "Error..."

      - name: Error handling
        run: exit 1
